// Code generated by MockGen. DO NOT EDIT.
// Source: authorised_miners_whitelist.go

// Package coterie is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)
